In [136]:
import pandas as pd
import csv
import os

In [159]:
subj_map = {
   'AndreiaVerdade': '0001',
   'BrunoDireito': '0002',
   'CarlosFerreira': '0003',
   'CarolinaTravassos': '0004',
   'CatarinaDuarte': '0005',
}

task_map = {
    'run-inner_run1-data': 'task-innerspeech_run-01',
    'run-inner_run2-data': 'task-innerspeech_run-02',
    'run-inner_run3-data': 'task-innerspeech_run-03',
}

#ROOT_DATA="/Users/home/Documents/data/"
#ROOT_DATA="/Volumes/LANGLYBACKU/DATA/DATA_Speech/"
ROOT_DATA="/media/brunomiguel/TOSHIBA EXT/DATA_Carlos_PhD_Final"

TR=2
CONDITIONS=['Baseline','Vogals','Syllables','Words','Phrases']

In [167]:
sname='AndreiaVerdade'
if sname in subj_map:
    print(subj_map[sname])
    sid=subj_map[sname]
    
    
tname='run-inner_run2-data'
if tname in task_map:
    print(task_map[tname])
    tcode=task_map[tname]

0001
task-innerspeech_run-02

In [168]:
# get .prt file
path=os.path.join(ROOT_DATA,sname,tname,'PROJECT','ANALYSIS')
prtfn = [f for f in os.listdir(path) if f.endswith('.prt')]

prtpath=os.path.join(path, prtfn[0])
print(prtpath)

/media/brunomiguel/TOSHIBA EXT/DATA_Carlos_PhD_Final/AndreiaVerdade/run-inner_run2-data/PROJECT/ANALYSIS/Run2.prt

In [169]:
# read .prt file

events_num=[]

onset=[]
duration=[]
trial_type=[]

# Open file.
with open(prtpath, newline = '') as f_reader:
    # Read next line.
    l=f_reader.readline()
    # Iterate conditions.
    for idx, c in enumerate(CONDITIONS):
        
        while not c in l:
            l = f_reader.readline()
            if not l:
                break
                
        # Read number of events of type c.
        events_num.append(int(f_reader.readline()))
        print('Condition - ' + c + ', number of repetitions - ' + str(events_num[idx]))
        
        # Iterate through events of type c.
        for e in range(int(events_num[idx])):
            temp_TR=f_reader.readline().split()
            
            # onset - TR to sec.
            onset_sec=(int(temp_TR[0])-1)*TR       
            onset.append(onset_sec)
            
            # duration - TR to sec
            duration_sec=(int(temp_TR[1])-(int(temp_TR[0])-1))*TR
            duration.append(duration_sec)
            trial_type.append(c)

Condition - Baseline, number of repetitions - 13
Condition - Vogals, number of repetitions - 3
Condition - Syllables, number of repetitions - 3
Condition - Words, number of repetitions - 3
Condition - Phrases, number of repetitions - 3

In [170]:
events = pd.DataFrame({'trial_type': trial_type,
                       'onset': onset,
                       'duration': duration})

In [171]:
events

   trial_type  onset  duration
0    Baseline      0        12
1    Baseline     42        12
2    Baseline     84        12
3    Baseline    126        12
4    Baseline    168        12
5    Baseline    210        12
6    Baseline    252        12
7    Baseline    294        12
8    Baseline    336        12
9    Baseline    378        12
10   Baseline    420        12
11   Baseline    462        12
12   Baseline    504        12
13     Vogals     96        30
14     Vogals    222        30
15     Vogals    348        30
16  Syllables     54        30
17  Syllables    180        30
18  Syllables    432        30
19      Words    138        30
20      Words    264        30
21      Words    390        30
22    Phrases     12        30
23    Phrases    306        30
24    Phrases    474        30

In [172]:
events=events.sort_values('onset')
events=events.reset_index(drop=True)
events

   trial_type  onset  duration
0    Baseline      0        12
1     Phrases     12        30
2    Baseline     42        12
3   Syllables     54        30
4    Baseline     84        12
5      Vogals     96        30
6    Baseline    126        12
7       Words    138        30
8    Baseline    168        12
9   Syllables    180        30
10   Baseline    210        12
11     Vogals    222        30
12   Baseline    252        12
13      Words    264        30
14   Baseline    294        12
15    Phrases    306        30
16   Baseline    336        12
17     Vogals    348        30
18   Baseline    378        12
19      Words    390        30
20   Baseline    420        12
21  Syllables    432        30
22   Baseline    462        12
23    Phrases    474        30
24   Baseline    504        12

In [173]:
ROOT_BIDS="/home/brunomiguel/Documents/data/BIDS_vswp"

eventspath=os.path.join(ROOT_BIDS,'sub-'+sid, 'ses-001','func')

eventsfn='sub-'+sid+'_ses-001_'+tcode+'_events.tsv'

eventspathfn=os.path.join(eventspath, eventsfn)

events.to_csv(eventspathfn, sep='\t', index=False)
print("Created the events file in %s " % eventspathfn)

Created the events file in /home/brunomiguel/Documents/data/BIDS_vswp/sub-0001/ses-001/func/sub-0001_ses-001_task-innerspeech_run-02_events.tsv