In [2]:
import pandas as pd
import csv
import os

In [13]:
subj_map = {
   'AlexandreSayal': '0001',
}

task_map = {
   'run-inner_run1-data': 'TBD',
}

#ROOT_DATA="/Users/home/Documents/data/"
ROOT_DATA="/Volumes/LANGLYBACKU/DATA/DATA_Speech/"

TR=2
CONDITIONS=['Baseline ', 'Vogals', 'Syllables', 'Words', 'Phrases']

In [14]:
sname='AlexandreSayal'
if sname in subj_map:
    print(subj_map[sname])
    sid=subj_map[sname]
    
    
tname='run-inner_run1-data'
if tname in task_map:
    print(task_map[tname])
    tcode=task_map[tname]

0001
TBD

In [15]:
# get .prt file
path=os.path.join(ROOT_DATA,sname,tname,'PROJECT','ANALYSIS')
prtfn = [f for f in os.listdir(path) if f.endswith('.prt')]

prtpath=os.path.join(path, prtfn[0])
print(prtpath)

/Volumes/LANGLYBACKU/DATA/DATA_Speech/AlexandreSayal/run-inner_run1-data/PROJECT/ANALYSIS/Run1.prt

In [16]:
# read .prt file

events_num=[]

onset=[]
duration=[]
trial_type=[]

# Open file.
with open(prtpath, newline = '') as f_reader:
    # Read next line.
    l=f_reader.readline()
    # Iterate conditions.
    for idx, c in enumerate(CONDITIONS):
        
        while not c in l:
            l = f_reader.readline()
            if not l:
                break
        # read number of events.
        events_num.append(int(f_reader.readline()))
        print(c,int(events_num[idx]))
        # read events
        for e in range(int(events_num[idx])):
            temp_TR=f_reader.readline().split()
            # onset - TR to sec
            onset_sec=(int(temp_TR[0])-1)*TR       
            onset.append(onset_sec)
            duration_sec=(int(temp_TR[1])-int(temp_TR[0]))*TR
            # duration - TR to sec
            duration.append(duration_sec)
            trial_type.append(c)

Baseline  13
Vogals 3
Syllables 3
Words 3
Phrases 3

In [17]:
events = pd.DataFrame({'trial_type': trial_type,
                       'onset': onset,
                       'duration': duration})

In [18]:
events

   trial_type  onset  duration
0   Baseline       0        10
1   Baseline      42        10
2   Baseline      84        10
3   Baseline     126        10
4   Baseline     168        10
5   Baseline     210        10
6   Baseline     252        10
7   Baseline     294        10
8   Baseline     336        10
9   Baseline     378        10
10  Baseline     420        10
11  Baseline     462        10
12  Baseline     504        10
13     Vogals     54        28
14     Vogals    264        28
15     Vogals    432        28
16  Syllables    138        28
17  Syllables    222        28
18  Syllables    348        28
19      Words     96        28
20      Words    306        28
21      Words    390        28
22    Phrases     12        28
23    Phrases    180        28
24    Phrases    474        28

In [9]:
events=events.sort_values('onset')
events=events.reset_index(drop=True)
events

   trial_type  onset  duration
0   Baseline     0.0      12.5
1     Phrases   15.0      35.0
2   Baseline    52.5      12.5
3      Vogals   67.5      35.0
4   Baseline   105.0      12.5
5       Words  120.0      35.0
6   Baseline   157.5      12.5
7   Syllables  172.5      35.0
8   Baseline   210.0      12.5
9     Phrases  225.0      35.0
10  Baseline   262.5      12.5
11  Syllables  277.5      35.0
12  Baseline   315.0      12.5
13     Vogals  330.0      35.0
14  Baseline   367.5      12.5
15      Words  382.5      35.0
16  Baseline   420.0      12.5
17  Syllables  435.0      35.0
18  Baseline   472.5      12.5
19      Words  487.5      35.0
20  Baseline   525.0      12.5
21     Vogals  540.0      35.0
22  Baseline   577.5      12.5
23    Phrases  592.5      35.0
24  Baseline   630.0      12.5

In [17]:
tsvfile = 'events_fonologico.tsv'
events.to_csv(tsvfile, sep='\t', index=False)
print("Created the events file in %s " % tsvfile)

Created the events file in events_fonologico.tsv

In [32]:
TR=2.5
onset_epoch=[]
duration_epoch=[]
trial_type_epoch=[]

for i in range(len(events)):
    idx_=((events['duration'][i]/TR))+1
    onset_=(events['onset'][i]) 
    for j in range(int(idx_)):   
        onset_epoch.append(onset_+(TR*j))
        duration_epoch.append(TR)
        trial_type_epoch.append(events['trial_type'][i])

events_epoch = pd.DataFrame({'trial_type': trial_type_epoch,
               'onset': onset_epoch,
               'duration': duration_epoch})

In [33]:
tsvfile = 'events_epoch_fonologico.tsv'
events_epoch.to_csv(tsvfile, sep='\t', index=False)
print("Created the events file in %s " % tsvfile)

Created the events file in events_epoch_fonologico.tsv

In [39]:
TR=2.5
num_events=216
betaseries_df=[]
onset_betaseries=[]
duration_betaseries=[]
trial_type_betaseries=[]

for i in range(num_events):
    onset_betaseries.append(TR*i)
    duration_betaseries.append(TR)
    trial_type_betaseries.append(i)

betaseries_df = pd.DataFrame({'trial_type': trial_type_betaseries,
               'onset': onset_betaseries,
               'duration': duration_betaseries})

In [40]:
tsvfile = 'betaseries_fonologico.tsv'
betaseries_df.to_csv(tsvfile, sep='\t', index=False)
print("Created the events file in %s " % tsvfile)

Created the events file in betaseries_fonologico.tsv